### PR TITLE
Create javacript.js

### PR DESCRIPTION
**Pull request by Kidd254**

### CODE REVIEW

**Review by Abenezer-Tilahun — COMMENTED** [review]
Hi @Kidd254 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights


## Required Changes ♻️

- [ ] Kindly Set up [a linter for HTML and CSS](https://github.com/microverseinc/linters-config) and make sure that any files that are not relevant are ignored by git.
- [ ] Please try to Add descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.
- [ ] Kindly make sure that your Pull Request should have a descriptive title telling you what changes are inside and a summary describing introduced changes in more detail.
- [ ] Kindly make sure that in your a .gitignore file listing " node_modules" directory. Your .gitignore look likes this : 
 
Capture

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Kidd254** [comment]
hi, thank you for the response... i have a question,, can you kindly
explain why the node_modules and not test.md filenot the one that needed to
be ignored...  [image: image.png]

**Comment by Abenezer-Tilahun** [comment]
Hello @Kidd254 one of the project requirement is When you Set up [a linter for HTML and CSS](https://github.com/microverseinc/linters-config) and make sure that any files that are not relevant are ignored by git. So when you run "npm init" on your terminal it will initialize the node_modules , so this file should not be present in your Repo to make sure that to document your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).

**Comment by Kidd254** [comment]
@Abenezer-Tilahun can i start over kindly instead of just making corrections

**Comment by Abenezer-Tilahun** [comment]
Hello @Kidd254 for second reviewer will only checkup  whether you address or not the requested changes so it better to make the correction rather than starting from the scratch.

**Comment by Kidd254** [comment]
Ok...Im working on it...thank you

**Pull request merged**
